
version: "2.4"
services:
  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-prerelease-20210114
    container_name: selenium-hub
    ports:
      - "4545:4444"
    networks:
      - selenium
  chrome:
    image: selenium/node-chrome-debug
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - NODE_MAX_INSTANCE=2
      - NODE_MAX_SESSION=2
    networks:
      - selenium
  search-module:
    image: shraddhal/seleniumtest2
    container_name: search-module
    depends_on:
      - chrome
    environment:
      - MODULE=search-module.xml
      - BROWSER=chrome
      - SELENIUM_HUB=selenium-hub
    volumes:
      - target/order-module-result:/output
networks:
  selenium:
    name: selenium
volumes:
  target/order-module-result:
    external: true

